x-php: &php
  image: pimcore/pimcore:php8.1.17-v1.3
  volumes:
    - ./:/var/www/html
  environment:
    MYSQL_SERVER_VERSION: "mariadb-10.5.13"

services:
  database:
    profiles: [ test ]
    image: mariadb:10.5.13
    command: >-
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: pimcore
      MYSQL_PASSWORD: pimcore
      MYSQL_USER: pimcore
    tmpfs:
      - /tmp
      - /var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s

  php-test:
    <<: *php
    profiles: [ test ]
    command: composer test
    depends_on:
      database:
        condition: service_healthy

  php:
    <<: *php
