services:
    _defaults:
        autowire: true
        autoconfigure: true

    Neusta\Pimcore\PresentationBundle\DocumentAreabrick\Code:
        tags: [ {name: 'pimcore.area.brick', id: 'code'} ]

    Neusta\Pimcore\PresentationBundle\DocumentAreabrick\Header:
        tags: [ {name: 'pimcore.area.brick', id: 'header'} ]

    Neusta\Pimcore\PresentationBundle\DocumentAreabrick\Image:
        tags: [ {name: 'pimcore.area.brick', id: 'image'} ]

    Neusta\Pimcore\PresentationBundle\DocumentAreabrick\Textarea:
        tags: [ {name: 'pimcore.area.brick', id: 'textarea'} ]

    Neusta\Pimcore\PresentationBundle\DocumentAreabrick\Wysiwyg:
        tags: [ {name: 'pimcore.area.brick', id: 'wysiwyg'} ]
