name: Tests

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: PHPUnit with PHP ${{ matrix.php-version }} ${{ matrix.dependencies }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: "8.1"
            dependencies: "lowest" # Pimcore 10.5.0
          - php-version: "8.1"
            dependencies: "highest" # Pimcore 11.*
          - php-version: "8.2"
            dependencies: "lowest" # Pimcore 10.5.0
          - php-version: "8.2"
            dependencies: "highest" # Pimcore 11.*

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Add Pimcore Admin UI
        run: composer require --dev pimcore/admin-ui-classic-bundle --no-interaction
        if: matrix.dependencies == 'highest'

      - name: Execute tests
        run: composer tests
